export const data = {
  products: [
    {
      _id: "1",
      slug: "1",
      name: "Full zip running shoes",
      category: "shoe",
      image: "../images/p1.jpeg",
      price: 100,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
      description: "Nike shoes iii   jsjklaj",
    },
    {
      _id: "2",
      slug: "2",
      name: "running clothes",
      category: "shirt",
      image: "../images/p2.webp",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
      description: "runiiing shoes is  dajljo",
    },
    {
      _id: "3",
      slug: "3",
      name: "running clothes",
      category: "shirt",
      image: "../images/p3.jpeg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
      description: "runiiing shoes is  dajljo",
    },
    {
      _id: "4",
      slug: "4",
      name: "running clothes",
      category: "shirt",
      image: "../images/p3.jpeg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
      description: "runiiing shoes is  dajljo",
    },
    {
      _id: "5",
      slug: "5",
      name: "running clothes",
      category: "shirt",
      image: "../images/p1.jpeg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 0,
      description: "runiiing shoes is  dajljo",
    },
  ],
};
